// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnGKUu9FXY7P7ZzAs8Cpnti_BieGEznXQ',
    appId: '1:710775723077:web:7c02e54617a83110d6bf2c',
    messagingSenderId: '710775723077',
    projectId: 'kisan-pro-c2c81',
    authDomain: 'kisan-pro-c2c81.firebaseapp.com',
    storageBucket: 'kisan-pro-c2c81.firebasestorage.app',
    measurementId: 'G-Y406PKGXXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLZyJyDanW3z_IYmITXoNgaYmylW202E',
    appId: '1:710775723077:android:e2f821ad12574b62d6bf2c',
    messagingSenderId: '710775723077',
    projectId: 'kisan-pro-c2c81',
    storageBucket: 'kisan-pro-c2c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5SC4gqeYZh8TP83n1jzGtUP6F8eEBJA',
    appId: '1:710775723077:ios:46d7d2d3fff57bb1d6bf2c',
    messagingSenderId: '710775723077',
    projectId: 'kisan-pro-c2c81',
    storageBucket: 'kisan-pro-c2c81.firebasestorage.app',
    iosBundleId: 'com.example.kisanProJrf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5SC4gqeYZh8TP83n1jzGtUP6F8eEBJA',
    appId: '1:710775723077:ios:46d7d2d3fff57bb1d6bf2c',
    messagingSenderId: '710775723077',
    projectId: 'kisan-pro-c2c81',
    storageBucket: 'kisan-pro-c2c81.firebasestorage.app',
    iosBundleId: 'com.example.kisanProJrf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnGKUu9FXY7P7ZzAs8Cpnti_BieGEznXQ',
    appId: '1:710775723077:web:9aa272ee038b6558d6bf2c',
    messagingSenderId: '710775723077',
    projectId: 'kisan-pro-c2c81',
    authDomain: 'kisan-pro-c2c81.firebaseapp.com',
    storageBucket: 'kisan-pro-c2c81.firebasestorage.app',
    measurementId: 'G-1D2S1JBQVK',
  );
}
